// license:BSD-3-Clause
//
// origin: src/xg/fx_params.h (1701 L, generated by tools/fxsweep) — machine-readable
// subset for the firmware-XG param layer: fx_def msb/lsb + per-param (addr, size) only.
// lo/hi/label/fmt/texts are display-only and are NOT read by xgtest/compare/sysfx —
// omitted here (ledger-disclosed deviation; regenerate from fx_params.h, never hand-edit;
// tools/fxsweep/make_fx_params.py remains the C++ side's canonical writer).
//
// fx_find keeps the disk two-pass order (exact msb/lsb, then lsb==0 fallback —
// fx_params.h:1687-1697). FX_DEFS order == fx_params.h order (ties matter there).

/// origin: fx_params.h:34-38 `fx_def` minus display fields
pub struct FxDef {
    pub msb: u8,
    pub lsb: u8,
    pub params: &'static [(u8, u8)], // (addr, size)
}

// origin: fx_params.h:715 (11 params)
static FX_01_00: [(u8, u8); 11] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x06, 1), (0x0b, 1), (0x20, 1), (0x21, 1), (0x22, 1), (0x23, 1), (0x24, 1),
];
// origin: fx_params.h:729 (12 params)
static FX_05_00: [(u8, u8); 12] = [
    (0x30, 2), (0x32, 2), (0x34, 2), (0x36, 2), (0x38, 2), (0x3a, 2), (0x3c, 2), (0x42, 2), (0x22, 1), (0x23, 1), (0x24, 1), (0x25, 1),
];
// origin: fx_params.h:744 (11 params)
static FX_06_00: [(u8, u8); 11] = [
    (0x30, 2), (0x32, 2), (0x34, 2), (0x36, 2), (0x38, 2), (0x3a, 2), (0x42, 2), (0x22, 1), (0x23, 1), (0x24, 1), (0x25, 1),
];
// origin: fx_params.h:758 (13 params)
static FX_07_00: [(u8, u8); 13] = [
    (0x30, 2), (0x32, 2), (0x34, 2), (0x36, 2), (0x38, 2), (0x3a, 2), (0x3c, 2), (0x3e, 2), (0x42, 2), (0x22, 1), (0x23, 1), (0x24, 1), (0x25, 1),
];
// origin: fx_params.h:774 (10 params)
static FX_08_00: [(u8, u8); 10] = [
    (0x30, 2), (0x32, 2), (0x34, 2), (0x36, 2), (0x38, 2), (0x42, 2), (0x22, 1), (0x23, 1), (0x24, 1), (0x25, 1),
];
// origin: fx_params.h:787 (11 params)
static FX_09_00: [(u8, u8); 11] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x06, 1), (0x07, 1), (0x08, 1), (0x0b, 1), (0x20, 1), (0x21, 1), (0x22, 1),
];
// origin: fx_params.h:801 (11 params)
static FX_0A_00: [(u8, u8); 11] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x06, 1), (0x07, 1), (0x08, 1), (0x0b, 1), (0x20, 1), (0x21, 1), (0x22, 1),
];
// origin: fx_params.h:815 (15 params)
static FX_10_00: [(u8, u8); 15] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x06, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x0b, 1), (0x20, 1), (0x21, 1), (0x22, 1), (0x23, 1), (0x24, 1),
];
// origin: fx_params.h:833 (5 params)
static FX_14_00: [(u8, u8); 5] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x0b, 1),
];
// origin: fx_params.h:841 (10 params)
static FX_15_00: [(u8, u8); 10] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x06, 1), (0x0b, 1), (0x22, 1), (0x23, 1), (0x24, 1), (0x25, 1),
];
// origin: fx_params.h:854 (11 params)
static FX_16_00: [(u8, u8); 11] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x06, 1), (0x07, 1), (0x0b, 1), (0x22, 1), (0x23, 1), (0x24, 1), (0x25, 1),
];
// origin: fx_params.h:868 (13 params)
static FX_41_00: [(u8, u8); 13] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x0b, 1), (0x20, 1), (0x21, 1), (0x22, 1), (0x24, 1),
];
// origin: fx_params.h:884 (13 params)
static FX_43_00: [(u8, u8); 13] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x0b, 1), (0x20, 1), (0x21, 1), (0x22, 1), (0x23, 1),
];
// origin: fx_params.h:900 (11 params)
static FX_44_00: [(u8, u8); 11] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x0b, 1), (0x20, 1), (0x21, 1), (0x22, 1),
];
// origin: fx_params.h:914 (10 params)
static FX_45_00: [(u8, u8); 10] = [
    (0x02, 1), (0x03, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x0b, 1), (0x20, 1), (0x21, 1), (0x22, 1),
];
// origin: fx_params.h:927 (10 params)
static FX_45_01: [(u8, u8); 10] = [
    (0x02, 1), (0x03, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x0b, 1), (0x23, 1), (0x24, 1), (0x25, 1),
];
// origin: fx_params.h:940 (11 params)
static FX_45_03: [(u8, u8); 11] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x0b, 1), (0x23, 1), (0x24, 1), (0x25, 1),
];
// origin: fx_params.h:954 (12 params)
static FX_46_00: [(u8, u8); 12] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x20, 1), (0x21, 1), (0x22, 1), (0x23, 1), (0x24, 1),
];
// origin: fx_params.h:969 (11 params)
static FX_47_00: [(u8, u8); 11] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x20, 1), (0x21, 1), (0x22, 1),
];
// origin: fx_params.h:983 (13 params)
static FX_47_01: [(u8, u8); 13] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x06, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x20, 1), (0x21, 1), (0x22, 1), (0x24, 1),
];
// origin: fx_params.h:999 (11 params)
static FX_48_00: [(u8, u8); 11] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x0b, 1), (0x20, 1), (0x21, 1),
];
// origin: fx_params.h:1013 (11 params)
static FX_48_08: [(u8, u8); 11] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x0b, 1), (0x20, 1), (0x22, 1),
];
// origin: fx_params.h:1027 (10 params)
static FX_49_00: [(u8, u8); 10] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x06, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x0b, 1), (0x20, 1),
];
// origin: fx_params.h:1040 (14 params)
static FX_49_01: [(u8, u8); 14] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x06, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x0b, 1), (0x20, 1), (0x21, 1), (0x22, 1), (0x23, 1), (0x24, 1),
];
// origin: fx_params.h:1057 (6 params)
static FX_4B_00: [(u8, u8); 6] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x0b, 1), (0x20, 1),
];
// origin: fx_params.h:1066 (5 params)
static FX_4B_01: [(u8, u8); 5] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x0b, 1),
];
// origin: fx_params.h:1074 (8 params)
static FX_4C_00: [(u8, u8); 8] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x06, 1), (0x07, 1), (0x08, 1), (0x24, 1),
];
// origin: fx_params.h:1085 (4 params)
static FX_4D_00: [(u8, u8); 4] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1),
];
// origin: fx_params.h:1092 (10 params)
static FX_4E_00: [(u8, u8); 10] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x0b, 1), (0x20, 1),
];
// origin: fx_params.h:1105 (14 params)
static FX_4E_01: [(u8, u8); 14] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x0b, 1), (0x20, 1), (0x21, 1), (0x22, 1), (0x23, 1), (0x24, 1),
];
// origin: fx_params.h:1122 (10 params)
static FX_50_00: [(u8, u8); 10] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x06, 1), (0x0b, 1), (0x20, 1), (0x21, 1), (0x22, 1), (0x23, 1),
];
// origin: fx_params.h:1135 (3 params)
static FX_51_00: [(u8, u8); 3] = [
    (0x02, 1), (0x03, 1), (0x04, 1),
];
// origin: fx_params.h:1141 (9 params)
static FX_52_00: [(u8, u8); 9] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x0b, 1), (0x20, 1),
];
// origin: fx_params.h:1153 (14 params)
static FX_52_02: [(u8, u8); 14] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x0b, 1), (0x20, 1), (0x21, 1), (0x22, 1), (0x23, 1), (0x24, 1), (0x25, 1),
];
// origin: fx_params.h:1170 (5 params)
static FX_53_00: [(u8, u8); 5] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x06, 1),
];
// origin: fx_params.h:1178 (4 params)
static FX_54_00: [(u8, u8); 4] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1),
];
// origin: fx_params.h:1185 (2 params)
static FX_55_00: [(u8, u8); 2] = [
    (0x20, 1), (0x21, 1),
];
// origin: fx_params.h:1190 (10 params)
static FX_56_00: [(u8, u8); 10] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x20, 1), (0x21, 1),
];
// origin: fx_params.h:1203 (13 params)
static FX_56_01: [(u8, u8); 13] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x20, 1), (0x21, 1), (0x23, 1), (0x24, 1), (0x25, 1),
];
// origin: fx_params.h:1219 (14 params)
static FX_56_03: [(u8, u8); 14] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x20, 1), (0x21, 1), (0x22, 1), (0x23, 1), (0x24, 1), (0x25, 1),
];
// origin: fx_params.h:1236 (8 params)
static FX_57_00: [(u8, u8); 8] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x0b, 1), (0x20, 1), (0x21, 1), (0x22, 1), (0x23, 1),
];
// origin: fx_params.h:1247 (7 params)
static FX_58_00: [(u8, u8); 7] = [
    (0x02, 1), (0x03, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x0b, 1),
];
// origin: fx_params.h:1257 (4 params)
static FX_5D_00: [(u8, u8); 4] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1),
];
// origin: fx_params.h:1264 (10 params)
static FX_5E_00: [(u8, u8); 10] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x06, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0b, 1), (0x24, 1),
];
// origin: fx_params.h:1277 (10 params)
static FX_5F_00: [(u8, u8); 10] = [
    (0x30, 2), (0x32, 2), (0x34, 2), (0x36, 2), (0x38, 2), (0x3a, 2), (0x3c, 2), (0x3e, 2), (0x40, 2), (0x42, 2),
];
// origin: fx_params.h:1290 (12 params)
static FX_60_00: [(u8, u8); 12] = [
    (0x30, 2), (0x32, 2), (0x34, 2), (0x36, 2), (0x38, 2), (0x3a, 2), (0x3c, 2), (0x42, 2), (0x20, 1), (0x21, 1), (0x22, 1), (0x23, 1),
];
// origin: fx_params.h:1305 (12 params)
static FX_61_00: [(u8, u8); 12] = [
    (0x30, 2), (0x32, 2), (0x34, 2), (0x36, 2), (0x38, 2), (0x3a, 2), (0x3c, 2), (0x42, 2), (0x20, 1), (0x21, 1), (0x22, 1), (0x23, 1),
];
// origin: fx_params.h:1320 (6 params)
static FX_62_00: [(u8, u8); 6] = [
    (0x30, 2), (0x32, 2), (0x34, 2), (0x36, 2), (0x38, 2), (0x42, 2),
];
// origin: fx_params.h:1329 (11 params)
static FX_62_01: [(u8, u8); 11] = [
    (0x30, 2), (0x32, 2), (0x34, 2), (0x36, 2), (0x38, 2), (0x3a, 2), (0x3c, 2), (0x3e, 2), (0x40, 2), (0x42, 2), (0x20, 1),
];
// origin: fx_params.h:1343 (14 params)
static FX_63_00: [(u8, u8); 14] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x06, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x20, 1), (0x21, 1), (0x22, 1), (0x23, 1), (0x24, 1),
];
// origin: fx_params.h:1360 (16 params)
static FX_68_00: [(u8, u8); 16] = [
    (0x30, 2), (0x32, 2), (0x34, 2), (0x36, 2), (0x38, 2), (0x3a, 2), (0x3c, 2), (0x3e, 2), (0x40, 2), (0x42, 2), (0x20, 1), (0x21, 1), (0x22, 1), (0x23, 1), (0x24, 1), (0x25, 1),
];
// origin: fx_params.h:1379 (5 params)
static FX_69_00: [(u8, u8); 5] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x06, 1),
];
// origin: fx_params.h:1387 (14 params)
static FX_6B_00: [(u8, u8); 14] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x06, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x0b, 1), (0x20, 1), (0x21, 1), (0x22, 1), (0x23, 1),
];
// origin: fx_params.h:1404 (12 params)
static FX_6C_00: [(u8, u8); 12] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x06, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x0b, 1), (0x20, 1), (0x22, 1),
];
// origin: fx_params.h:1419 (14 params)
static FX_6D_00: [(u8, u8); 14] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x06, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x0b, 1), (0x22, 1), (0x23, 1), (0x24, 1), (0x25, 1),
];
// origin: fx_params.h:1436 (14 params)
static FX_6E_00: [(u8, u8); 14] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x06, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x0b, 1), (0x22, 1), (0x23, 1), (0x24, 1), (0x25, 1),
];
// origin: fx_params.h:1453 (14 params)
static FX_6F_00: [(u8, u8); 14] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x06, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0b, 1), (0x20, 1), (0x22, 1), (0x23, 1), (0x24, 1), (0x25, 1),
];
// origin: fx_params.h:1470 (14 params)
static FX_70_00: [(u8, u8); 14] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x06, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x0b, 1), (0x22, 1), (0x23, 1), (0x24, 1), (0x25, 1),
];
// origin: fx_params.h:1487 (12 params)
static FX_71_00: [(u8, u8); 12] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x06, 1), (0x07, 1), (0x08, 1), (0x0b, 1), (0x22, 1), (0x23, 1), (0x24, 1), (0x25, 1),
];
// origin: fx_params.h:1502 (14 params)
static FX_72_00: [(u8, u8); 14] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x06, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x0b, 1), (0x22, 1), (0x23, 1), (0x24, 1), (0x25, 1),
];
// origin: fx_params.h:1519 (7 params)
static FX_73_00: [(u8, u8); 7] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x06, 1), (0x07, 1), (0x08, 1),
];
// origin: fx_params.h:1529 (7 params)
static FX_74_00: [(u8, u8); 7] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x06, 1), (0x07, 1), (0x0b, 1),
];
// origin: fx_params.h:1539 (11 params)
static FX_75_00: [(u8, u8); 11] = [
    (0x02, 1), (0x03, 1), (0x04, 1), (0x05, 1), (0x06, 1), (0x07, 1), (0x08, 1), (0x09, 1), (0x0a, 1), (0x20, 1), (0x21, 1),
];
// origin: fx_params.h:1553 (11 params)
static FX_76_00: [(u8, u8); 11] = [
    (0x30, 2), (0x32, 2), (0x34, 2), (0x36, 2), (0x38, 2), (0x3a, 2), (0x3c, 2), (0x3e, 2), (0x40, 2), (0x42, 2), (0x20, 1),
];

/// origin: fx_params.h FX_DEFS table (:1560-1684 region) — same order.
static FX_DEFS: &[FxDef] = &[
    FxDef { msb: 0x01, lsb: 0x00, params: &FX_01_00 }, // :1568
    FxDef { msb: 0x01, lsb: 0x01, params: &FX_01_00 }, // :1569
    FxDef { msb: 0x01, lsb: 0x06, params: &FX_01_00 }, // :1570
    FxDef { msb: 0x01, lsb: 0x07, params: &FX_01_00 }, // :1571
    FxDef { msb: 0x02, lsb: 0x00, params: &FX_01_00 }, // :1572
    FxDef { msb: 0x02, lsb: 0x01, params: &FX_01_00 }, // :1573
    FxDef { msb: 0x02, lsb: 0x02, params: &FX_01_00 }, // :1574
    FxDef { msb: 0x02, lsb: 0x05, params: &FX_01_00 }, // :1575
    FxDef { msb: 0x02, lsb: 0x06, params: &FX_01_00 }, // :1576
    FxDef { msb: 0x02, lsb: 0x07, params: &FX_01_00 }, // :1577
    FxDef { msb: 0x03, lsb: 0x00, params: &FX_01_00 }, // :1578
    FxDef { msb: 0x03, lsb: 0x01, params: &FX_01_00 }, // :1579
    FxDef { msb: 0x04, lsb: 0x00, params: &FX_01_00 }, // :1580
    FxDef { msb: 0x04, lsb: 0x07, params: &FX_01_00 }, // :1581
    FxDef { msb: 0x05, lsb: 0x00, params: &FX_05_00 }, // :1582
    FxDef { msb: 0x06, lsb: 0x00, params: &FX_06_00 }, // :1583
    FxDef { msb: 0x07, lsb: 0x00, params: &FX_07_00 }, // :1584
    FxDef { msb: 0x08, lsb: 0x00, params: &FX_08_00 }, // :1585
    FxDef { msb: 0x09, lsb: 0x00, params: &FX_09_00 }, // :1586
    FxDef { msb: 0x09, lsb: 0x01, params: &FX_09_00 }, // :1587
    FxDef { msb: 0x0a, lsb: 0x00, params: &FX_0A_00 }, // :1588
    FxDef { msb: 0x0b, lsb: 0x00, params: &FX_0A_00 }, // :1589
    FxDef { msb: 0x10, lsb: 0x00, params: &FX_10_00 }, // :1590
    FxDef { msb: 0x11, lsb: 0x00, params: &FX_10_00 }, // :1591
    FxDef { msb: 0x12, lsb: 0x00, params: &FX_10_00 }, // :1592
    FxDef { msb: 0x13, lsb: 0x00, params: &FX_10_00 }, // :1593
    FxDef { msb: 0x14, lsb: 0x00, params: &FX_14_00 }, // :1594
    FxDef { msb: 0x14, lsb: 0x01, params: &FX_14_00 }, // :1595
    FxDef { msb: 0x14, lsb: 0x02, params: &FX_14_00 }, // :1596
    FxDef { msb: 0x15, lsb: 0x00, params: &FX_15_00 }, // :1597
    FxDef { msb: 0x15, lsb: 0x08, params: &FX_15_00 }, // :1598
    FxDef { msb: 0x16, lsb: 0x00, params: &FX_16_00 }, // :1599
    FxDef { msb: 0x41, lsb: 0x00, params: &FX_41_00 }, // :1600
    FxDef { msb: 0x41, lsb: 0x01, params: &FX_41_00 }, // :1601
    FxDef { msb: 0x41, lsb: 0x02, params: &FX_41_00 }, // :1602
    FxDef { msb: 0x41, lsb: 0x03, params: &FX_41_00 }, // :1603
    FxDef { msb: 0x41, lsb: 0x04, params: &FX_41_00 }, // :1604
    FxDef { msb: 0x41, lsb: 0x05, params: &FX_41_00 }, // :1605
    FxDef { msb: 0x41, lsb: 0x06, params: &FX_41_00 }, // :1606
    FxDef { msb: 0x41, lsb: 0x07, params: &FX_41_00 }, // :1607
    FxDef { msb: 0x41, lsb: 0x08, params: &FX_41_00 }, // :1608
    FxDef { msb: 0x42, lsb: 0x00, params: &FX_41_00 }, // :1609
    FxDef { msb: 0x42, lsb: 0x01, params: &FX_41_00 }, // :1610
    FxDef { msb: 0x42, lsb: 0x02, params: &FX_41_00 }, // :1611
    FxDef { msb: 0x42, lsb: 0x08, params: &FX_41_00 }, // :1612
    FxDef { msb: 0x43, lsb: 0x00, params: &FX_43_00 }, // :1613
    FxDef { msb: 0x43, lsb: 0x01, params: &FX_43_00 }, // :1614
    FxDef { msb: 0x43, lsb: 0x07, params: &FX_43_00 }, // :1615
    FxDef { msb: 0x43, lsb: 0x08, params: &FX_43_00 }, // :1616
    FxDef { msb: 0x44, lsb: 0x00, params: &FX_44_00 }, // :1617
    FxDef { msb: 0x45, lsb: 0x00, params: &FX_45_00 }, // :1618
    FxDef { msb: 0x45, lsb: 0x01, params: &FX_45_01 }, // :1619
    FxDef { msb: 0x45, lsb: 0x02, params: &FX_45_01 }, // :1620
    FxDef { msb: 0x45, lsb: 0x03, params: &FX_45_03 }, // :1621
    FxDef { msb: 0x46, lsb: 0x00, params: &FX_46_00 }, // :1622
    FxDef { msb: 0x47, lsb: 0x00, params: &FX_47_00 }, // :1623
    FxDef { msb: 0x47, lsb: 0x01, params: &FX_47_01 }, // :1624
    FxDef { msb: 0x48, lsb: 0x00, params: &FX_48_00 }, // :1625
    FxDef { msb: 0x48, lsb: 0x08, params: &FX_48_08 }, // :1626
    FxDef { msb: 0x49, lsb: 0x00, params: &FX_49_00 }, // :1627
    FxDef { msb: 0x49, lsb: 0x01, params: &FX_49_01 }, // :1628
    FxDef { msb: 0x49, lsb: 0x08, params: &FX_49_00 }, // :1629
    FxDef { msb: 0x4a, lsb: 0x00, params: &FX_49_00 }, // :1630
    FxDef { msb: 0x4a, lsb: 0x08, params: &FX_49_00 }, // :1631
    FxDef { msb: 0x4b, lsb: 0x00, params: &FX_4B_00 }, // :1632
    FxDef { msb: 0x4b, lsb: 0x01, params: &FX_4B_01 }, // :1633
    FxDef { msb: 0x4b, lsb: 0x08, params: &FX_4B_00 }, // :1634
    FxDef { msb: 0x4c, lsb: 0x00, params: &FX_4C_00 }, // :1635
    FxDef { msb: 0x4d, lsb: 0x00, params: &FX_4D_00 }, // :1636
    FxDef { msb: 0x4e, lsb: 0x00, params: &FX_4E_00 }, // :1637
    FxDef { msb: 0x4e, lsb: 0x01, params: &FX_4E_01 }, // :1638
    FxDef { msb: 0x4e, lsb: 0x02, params: &FX_4E_01 }, // :1639
    FxDef { msb: 0x50, lsb: 0x00, params: &FX_50_00 }, // :1640
    FxDef { msb: 0x50, lsb: 0x01, params: &FX_50_00 }, // :1641
    FxDef { msb: 0x51, lsb: 0x00, params: &FX_51_00 }, // :1642
    FxDef { msb: 0x52, lsb: 0x00, params: &FX_52_00 }, // :1643
    FxDef { msb: 0x52, lsb: 0x01, params: &FX_52_00 }, // :1644
    FxDef { msb: 0x52, lsb: 0x02, params: &FX_52_02 }, // :1645
    FxDef { msb: 0x52, lsb: 0x08, params: &FX_52_02 }, // :1646
    FxDef { msb: 0x53, lsb: 0x00, params: &FX_53_00 }, // :1647
    FxDef { msb: 0x54, lsb: 0x00, params: &FX_54_00 }, // :1648
    FxDef { msb: 0x55, lsb: 0x00, params: &FX_55_00 }, // :1649
    FxDef { msb: 0x56, lsb: 0x00, params: &FX_56_00 }, // :1650
    FxDef { msb: 0x56, lsb: 0x01, params: &FX_56_01 }, // :1651
    FxDef { msb: 0x56, lsb: 0x02, params: &FX_56_01 }, // :1652
    FxDef { msb: 0x56, lsb: 0x03, params: &FX_56_03 }, // :1653
    FxDef { msb: 0x57, lsb: 0x00, params: &FX_57_00 }, // :1654
    FxDef { msb: 0x58, lsb: 0x00, params: &FX_58_00 }, // :1655
    FxDef { msb: 0x5d, lsb: 0x00, params: &FX_5D_00 }, // :1656
    FxDef { msb: 0x5e, lsb: 0x00, params: &FX_5E_00 }, // :1657
    FxDef { msb: 0x5f, lsb: 0x00, params: &FX_5F_00 }, // :1658
    FxDef { msb: 0x5f, lsb: 0x01, params: &FX_5F_00 }, // :1659
    FxDef { msb: 0x60, lsb: 0x00, params: &FX_60_00 }, // :1660
    FxDef { msb: 0x60, lsb: 0x01, params: &FX_60_00 }, // :1661
    FxDef { msb: 0x61, lsb: 0x00, params: &FX_61_00 }, // :1662
    FxDef { msb: 0x61, lsb: 0x01, params: &FX_61_00 }, // :1663
    FxDef { msb: 0x62, lsb: 0x00, params: &FX_62_00 }, // :1664
    FxDef { msb: 0x62, lsb: 0x01, params: &FX_62_01 }, // :1665
    FxDef { msb: 0x62, lsb: 0x02, params: &FX_62_00 }, // :1666
    FxDef { msb: 0x62, lsb: 0x03, params: &FX_62_01 }, // :1667
    FxDef { msb: 0x63, lsb: 0x00, params: &FX_63_00 }, // :1668
    FxDef { msb: 0x63, lsb: 0x01, params: &FX_63_00 }, // :1669
    FxDef { msb: 0x68, lsb: 0x00, params: &FX_68_00 }, // :1670
    FxDef { msb: 0x69, lsb: 0x00, params: &FX_69_00 }, // :1671
    FxDef { msb: 0x6b, lsb: 0x00, params: &FX_6B_00 }, // :1672
    FxDef { msb: 0x6c, lsb: 0x00, params: &FX_6C_00 }, // :1673
    FxDef { msb: 0x6d, lsb: 0x00, params: &FX_6D_00 }, // :1674
    FxDef { msb: 0x6e, lsb: 0x00, params: &FX_6E_00 }, // :1675
    FxDef { msb: 0x6f, lsb: 0x00, params: &FX_6F_00 }, // :1676
    FxDef { msb: 0x70, lsb: 0x00, params: &FX_70_00 }, // :1677
    FxDef { msb: 0x71, lsb: 0x00, params: &FX_71_00 }, // :1678
    FxDef { msb: 0x72, lsb: 0x00, params: &FX_72_00 }, // :1679
    FxDef { msb: 0x73, lsb: 0x00, params: &FX_73_00 }, // :1680
    FxDef { msb: 0x74, lsb: 0x00, params: &FX_74_00 }, // :1681
    FxDef { msb: 0x75, lsb: 0x00, params: &FX_75_00 }, // :1682
    FxDef { msb: 0x76, lsb: 0x00, params: &FX_76_00 }, // :1683
];

/// origin: fx_params.h:1687-1697 `fx_find` — exact msb/lsb first, then the
/// same-MSB LSB-0 table, else None
pub fn fx_find(kind: i32) -> Option<&'static FxDef> {
    let msb = (kind >> 7) as u8; // :1689 int shift then u8 compare
    let lsb = (kind & 0x7f) as u8;
    for d in FX_DEFS {
        if d.msb as i32 == msb as i32 && d.lsb as i32 == lsb as i32 {
            return Some(d);
        }
    }
    for d in FX_DEFS {
        if d.msb as i32 == msb as i32 && d.lsb as i32 == 0 {
            return Some(d);
        }
    }
    None // :1696
}

/// number of FX_DEFS rows (regen cross-check vs fx_params.h)
pub fn fx_def_count() -> usize {
    FX_DEFS.len()
}
